apiVersion: v1
kind: Service
metadata:
   name: datasiv-zks
   namespace: dev
   labels:
      service: datasiv-zks
      env: dev
spec:
   clusterIP: None
   ports:
     - name: client
       port: 2181
       targetPort: 2181
     - name: peer
       port: 2888
       targetPort: 2888
     - name: leader
       port: 3888
       targetPort: 3888
   publishNotReadyAddresses: true
   selector:
      service: datasiv-zks
      env: dev
   type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
   name: datasiv-zks-ui
   namespace: dev
   annotations:
      cloud.google.com/load-balancer-type: "Internal"
   labels:
      service: datasiv-zks
      env: dev
spec:
   ports:
     - name: client
       nodePort: 32226
       port: 2181
       targetPort: 2181
   selector:
      service: datasiv-zks
      env: dev
   type: LoadBalancer
   loadBalancerIP: "10.131.0.21"
   loadBalancerSourceRanges:
      - 10.0.0.0/8
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: datasiv-zks
   namespace: dev
   labels:
      service: datasiv-zks
      env: dev
spec:
   replicas: 1
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxUnavailable: 1
         maxSurge: 1
   selector:
      matchLabels:
         service: datasiv-zks
         env: dev
   template:
      metadata:
         labels:
            service: datasiv-zks
            env: dev
      spec:
         containers:
            - name: datasiv-zks
              image: bitnami/zookeeper:3.4.12
              imagePullPolicy: Always
              ports:
                - name: client
                  containerPort: 2181
                - name: peer
                  containerPort: 2888
                - name: leader
                  containerPort: 3888
              env:
                - name: ZOO_ENABLE_AUTH
                  value: "no"
                - name: ALLOW_ANONYMOUS_LOGIN
                  value: "yes"
              resources:
                 requests:
                    memory: "600M"
                    cpu: "100m"
                 limits:
                    memory: "1G"
                    cpu: "200m"
